services:
  - type: web
    name: airdrop-bot
    env: node             # OK, spécifie Node.js
    plan: free            # OK, plan gratuit
    buildCommand: npm install  # OK, installe les dépendances
    startCommand: node index.js  # OK, lance ton serveur
    envVars:
      - key: PORT
        value: 10000      # OK, fixe le port à 10000 (mais Render fournit aussi une variable PORT automatiquement)
      - key: NODE_ENV
        value: production
      - key: PUBLIC_URL
        value: https://airdrop-bot-soy1.onrender.com
      - key: TELEGRAM_BOT_TOKEN
        fromService:
          name: telegram-secrets
          type: secret
