services:
  - type: web
    name: airdrop-bot
    env: node  # Force Render à utiliser Node.js
    plan: free
    buildCommand: npm install  # Pas besoin de Python
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: PUBLIC_URL
        value: https://faucet-app.onrender.com
      - key: TELEGRAM_BOT_TOKEN
        fromService:
          name: telegram-secrets
          type: secret